name: aospy-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - sphinx=1.4.1
  - numpy=1.11
  - numpydoc=0.6
  - scipy=0.18.1
  - pandas=0.19.0
  - hdf4
  - netCDF4
  - xarray=0.8.2
  - ipython=5.1.0
  - matplotlib=1.5.3